# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodels',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
